#
# Check YAML syntx here http://www.yamllint.com/ if you are having formatting issues
#


nuvo:
  # Static IP for connection through global cache device on port #
  host: <ip for global cache>
  port: <serial port for global cache>
  name: Nuvo e6dms

zones:
  3:
    name: Custom Zone Name